# Base configs
# base URL after / is dependent on the repository name
# baseurl: "https://dauve318g787.github.io/david-dupuis-photography"
baseurl: "" # Comment the above line and uncomment this to test the website locally
favicon: "/favicon.ico"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "David Dupuis Photography"
subtitle: "My Photography Journey"
author: "David Dupuis"
header:
 title: "David Dupuis"
 subtitle: "Photography"
footer:
 name: "Hello and welcome!"
 bio: "My name is David Dupuis! I've been taking photos ever since I was a little kid, when my parents let me play around with their Canon point and shoot on family vacations. Since I purchased my first DSLR in 2017, I have photographed
 everything from landscapes to planes to trains to sports, and even won a photo contest along the way! My current focus is on sports photography, and I also do a little writing on the side- check that out <a href=\"https://victormorganmedia.com/pba\">here!</a>
 Thank you for stopping by, and I hope you enjoy!"
 github: "If you have time, check out my <a href=\"https://github.com/Dauve318G787\">GitHub</a> ;)"
# web_design: "LW"
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks

exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "eye"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
social_urls:
  # twitter: ""
  # instagram: ""
  # dribbble: ""
  linkedin: "https://www.linkedin.com/in/david-dupuis-175b18208/"
  github: "https://www.github.com/Dauve318G787"
